language: python
python:
- "3.7"
install: "pip3 install -r requirements.txt"
script: 
- "make travis"

after_success:
  deploy:
    provider: heroku
    api_key: "400396e8-17a7-4b9f-96d5-5aa7ce1cb91d"
    app: dry-river-74760