language: python
python:
- "3.7"
install: "pip3 install -r requirements.txt"
script: 
- "make travis"

deploy:
  provider: heroku
  api_key: "35ed7263-f3c1-4a3c-ac36-2e0c720b3593"
  app: dry-river-74760