language: python
python: "3.7"

install: 
- "pip3 install -r requirements.txt" 
script:
- "nvm install 10.21.0"
- "nvm use 10.21.0"
- "make travis"

after_failure:
  - rm source/.coverage
  - echo "unit test failure"
  - travis_terminate 1

after_success:
  - "make coverage"

deploy:
  provider: heroku
  api_key: "35ed7263-f3c1-4a3c-ac36-2e0c720b3593"
  app: dry-river-74760
  on:
    branch: master